"""Challenge — a concrete task auto-generated by the Challenge Designer.

Each challenge defines what Claude is asked to do, how the output is graded,
and what verification method (tests, judge review, etc.) applies.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Challenge:
    """A single evaluation challenge for competing Skills."""

    id: str
    prompt: str
    difficulty: str  # easy | medium | hard
    evaluation_criteria: dict[str, float] = field(default_factory=dict)
    verification_method: str = "judge_review"  # run_tests | judge_review | both
    setup_files: dict[str, str] = field(default_factory=dict)
    gold_standard_hints: str = ""

    def to_dict(self) -> dict:
        """Serialize to a JSON-safe dict."""
        return {
            "id": self.id,
            "prompt": self.prompt,
            "difficulty": self.difficulty,
            "evaluation_criteria": self.evaluation_criteria,
            "verification_method": self.verification_method,
            "setup_files": self.setup_files,
            "gold_standard_hints": self.gold_standard_hints,
        }

    @classmethod
    def from_dict(cls, data: dict) -> Challenge:
        """Rehydrate from a dict."""
        return cls(
            id=data["id"],
            prompt=data["prompt"],
            difficulty=data["difficulty"],
            evaluation_criteria=data.get("evaluation_criteria", {}),
            verification_method=data.get("verification_method", "judge_review"),
            setup_files=data.get("setup_files", {}),
            gold_standard_hints=data.get("gold_standard_hints", ""),
        )
