"""Challenge — a concrete task auto-generated by the Challenge Designer.

Each challenge defines what Claude is asked to do, how the output is graded,
and what verification method (tests, judge review, etc.) applies.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Challenge:
    """A single evaluation challenge for competing Skills."""

    id: str
    prompt: str
    difficulty: str  # easy | medium | hard
    evaluation_criteria: dict[str, float] = field(default_factory=dict)
    verification_method: str = "judge_review"  # run_tests | judge_review | both
    setup_files: dict[str, str] = field(default_factory=dict)
    gold_standard_hints: str = ""

    def to_dict(self) -> dict:
        """Serialize. Implemented in Step 4."""
        raise NotImplementedError

    @classmethod
    def from_dict(cls, data: dict) -> Challenge:
        """Rehydrate. Implemented in Step 4."""
        raise NotImplementedError
