"""Orchestrates the 6-layer judging pipeline in order.

L1 Deterministic → L2 Trigger Accuracy → L3 Trace Analysis →
L4 Comparative + Pareto → L5 Trait Attribution → (L6 Consistency, v1.1).

Each layer's outputs populate specific fields on the ``CompetitionResult``
objects and, in aggregate, on the ``Generation``. The pipeline is the only
place where per-layer output is composed into generation-level fitness.
"""

from __future__ import annotations

import json

from skillforge.agents.judge.attribution import run_l5
from skillforge.agents.judge.comparative import run_l4
from skillforge.agents.judge.deterministic import run_l1
from skillforge.agents.judge.trace_analysis import run_l3
from skillforge.agents.judge.trigger import run_l2
from skillforge.models import Challenge, Generation, SkillGenome

# Default eval queries used when a Challenge doesn't carry its own.
# Loaded lazily from docs/eval-queries-template.json.
_DEFAULT_EVAL_QUERIES: dict | None = None


def _load_default_eval_queries() -> dict:
    """Load docs/eval-queries-template.json once, memoized."""
    global _DEFAULT_EVAL_QUERIES
    if _DEFAULT_EVAL_QUERIES is not None:
        return _DEFAULT_EVAL_QUERIES
    from skillforge.config import DOCS_DIR

    path = DOCS_DIR / "eval-queries-template.json"
    if not path.exists():
        _DEFAULT_EVAL_QUERIES = {"should_trigger": [], "should_not_trigger": []}
        return _DEFAULT_EVAL_QUERIES
    try:
        _DEFAULT_EVAL_QUERIES = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        _DEFAULT_EVAL_QUERIES = {"should_trigger": [], "should_not_trigger": []}
    return _DEFAULT_EVAL_QUERIES


def _eval_queries_for(skill: SkillGenome) -> tuple[list[str], list[str]]:
    """Return (should_trigger, should_not_trigger) for a skill.

    MVP: always returns the template defaults. A later step may attach
    skill-specific eval queries (e.g., generated by the Challenge Designer
    alongside the challenges) on the SkillGenome or the Generation.
    """
    defaults = _load_default_eval_queries()
    return (
        defaults.get("should_trigger", []),
        defaults.get("should_not_trigger", []),
    )


async def run_judging_pipeline(
    generation: Generation,
    challenges: list[Challenge],
    run_id: str | None = None,
) -> Generation:
    """Execute all judging layers in order; return the enriched generation.

    Mutates the ``generation`` in place (its ``results`` and ``skills``
    get fitness fields populated) and also returns it for chaining.

    Order:
        1. L1 deterministic on every (result, challenge) pair
        2. L2 trigger accuracy on every unique skill (one batched call per skill)
        3. L3 trace analysis on every (result, skill) pair
        4. L4 comparative + Pareto on the full result set (computes front)
        5. L5 trait attribution on every (result, skill) pair
        6. Aggregate per-skill scores onto each SkillGenome
        7. Compute generation-level best_fitness, avg_fitness, pareto_front
    """
    # Build lookups by ID (challenges and skills). Duplicates are fine —
    # the last one wins (they should be equal anyway).
    challenge_by_id: dict[str, Challenge] = {c.id: c for c in challenges}
    skill_by_id: dict[str, SkillGenome] = {s.id: s for s in generation.skills}

    # ---- L1: deterministic ---------------------------------------------------
    for result in generation.results:
        challenge = challenge_by_id.get(result.challenge_id)
        if challenge is None:
            continue
        await run_l1(result, challenge)

    if run_id:
        from skillforge.engine.events import emit
        await emit(run_id, "judging_layer_complete", layer=1, generation=generation.number)

    # ---- L2: trigger accuracy (one batched call per unique skill) -----------
    # L2 is per-skill, not per-result. Compute once and stamp the same
    # (precision, recall) on every result for that skill.
    trigger_scores: dict[str, tuple[float, float]] = {}
    for skill in generation.skills:
        should_trigger, should_not_trigger = _eval_queries_for(skill)
        if not should_trigger and not should_not_trigger:
            trigger_scores[skill.id] = (0.0, 0.0)
            continue
        trigger_scores[skill.id] = await run_l2(
            skill, should_trigger, should_not_trigger
        )

    for result in generation.results:
        precision, recall = trigger_scores.get(result.skill_id, (0.0, 0.0))
        result.trigger_precision = precision
        result.trigger_recall = recall

    if run_id:
        from skillforge.engine.events import emit
        await emit(run_id, "judging_layer_complete", layer=2, generation=generation.number)

    # ---- L3: trace analysis --------------------------------------------------
    for result in generation.results:
        skill = skill_by_id.get(result.skill_id)
        if skill is None:
            continue
        await run_l3(result, skill)

    if run_id:
        from skillforge.engine.events import emit
        await emit(run_id, "judging_layer_complete", layer=3, generation=generation.number)

    # ---- L4: comparative + Pareto (operates on the full result set) ---------
    l4_output = await run_l4(generation.results)
    pareto_optimal_result_ids = set(l4_output.get("pareto_optimal_ids", []))

    if run_id:
        from skillforge.engine.events import emit
        await emit(run_id, "judging_layer_complete", layer=4, generation=generation.number)

    # ---- L5: trait attribution ----------------------------------------------
    for result in generation.results:
        skill = skill_by_id.get(result.skill_id)
        if skill is None:
            continue
        await run_l5(result, skill)

    if run_id:
        from skillforge.engine.events import emit
        await emit(run_id, "judging_layer_complete", layer=5, generation=generation.number)

    # ---- Aggregate per-skill fitness onto each SkillGenome ------------------
    # A skill may compete against multiple challenges; aggregate across them.
    for skill in generation.skills:
        skill_results = [r for r in generation.results if r.skill_id == skill.id]
        if not skill_results:
            continue

        # Average Pareto objectives across this skill's challenge results
        objective_keys = set()
        for r in skill_results:
            objective_keys.update(r.pareto_objectives.keys())
        skill.pareto_objectives = {
            k: sum(r.pareto_objectives.get(k, 0.0) for r in skill_results) / len(skill_results)
            for k in objective_keys
        }

        # Trigger scores (same across all results for a skill — take the first)
        skill.trigger_precision = skill_results[0].trigger_precision
        skill.trigger_recall = skill_results[0].trigger_recall

        # Behavioral signature: concat first result's signature (MVP heuristic)
        skill.behavioral_signature = skill_results[0].behavioral_signature

        # Deterministic scores: per-challenge compile/tests/lint
        det_scores: dict[str, float] = {}
        for r in skill_results:
            prefix = r.challenge_id[:8]
            det_scores[f"{prefix}:compiles"] = 1.0 if r.compiles else 0.0
            if r.tests_pass is not None:
                det_scores[f"{prefix}:tests"] = 1.0 if r.tests_pass else 0.0
            if r.lint_score is not None:
                det_scores[f"{prefix}:lint"] = r.lint_score
        skill.deterministic_scores = det_scores

        # Trait attribution: average contributions across all results
        all_traits: set[str] = set()
        for r in skill_results:
            all_traits.update(r.trait_contribution.keys())
        skill.trait_attribution = {
            t: sum(r.trait_contribution.get(t, 0.0) for r in skill_results) / len(skill_results)
            for t in all_traits
        }
        # Trait diagnostics: take the most-recent non-empty diagnostic per trait
        skill.trait_diagnostics = {}
        for t in all_traits:
            for r in skill_results:
                diag = r.trait_diagnostics.get(t, "")
                if diag:
                    skill.trait_diagnostics[t] = diag
                    break

        # Pareto optimality: a skill is Pareto-optimal if ANY of its results is
        skill.is_pareto_optimal = any(
            r.skill_id in pareto_optimal_result_ids
            or id(r) in pareto_optimal_result_ids
            for r in skill_results
        )

    # ---- Generation-level aggregates ----------------------------------------
    # Pareto front at the generation level = skill IDs whose results landed
    # on the Pareto front. De-duplicated.
    generation.pareto_front = [s.id for s in generation.skills if s.is_pareto_optimal]

    # best_fitness / avg_fitness: use an aggregate of Pareto objectives as a
    # scalar for ranking purposes (the Pareto front is the real answer; this
    # is just a summary number for charts).
    per_skill_scalar: list[float] = []
    for skill in generation.skills:
        if not skill.pareto_objectives:
            continue
        scalar = sum(skill.pareto_objectives.values()) / len(skill.pareto_objectives)
        per_skill_scalar.append(scalar)

    if per_skill_scalar:
        generation.best_fitness = max(per_skill_scalar)
        generation.avg_fitness = sum(per_skill_scalar) / len(per_skill_scalar)
    else:
        generation.best_fitness = 0.0
        generation.avg_fitness = 0.0

    return generation
