/**
 * Transparent rubric comparing the generated skill package against the
 * Skill Authoring Constraints in CLAUDE.md. Pure presentational —
 * takes the installable file list and computes presence.
 */
import { useMemo } from "react";

import type { VirtualFile } from "./types";

interface GoldStandardChecklistProps {
  installable: VirtualFile[];
}

type ChecklistItem = {
  path: string;
  label: string;
  kind: "required" | "recommended" | "optional";
  present: boolean;
};

function buildChecklist(installable: VirtualFile[]): ChecklistItem[] {
  const present = new Set(installable.map((f) => f.path));
  const pathStartsWith = (prefix: string) => Array.from(present).some((p) => p.startsWith(prefix));

  return [
    {
      path: "SKILL.md",
      label: "SKILL.md with frontmatter + body",
      kind: "required",
      present: present.has("SKILL.md"),
    },
    {
      path: "scripts/validate.sh",
      label: "scripts/validate.sh (structural self-check)",
      kind: "recommended",
      present: present.has("scripts/validate.sh"),
    },
    {
      path: "scripts/main_helper.py",
      label: "scripts/main_helper.py (deterministic helper)",
      kind: "recommended",
      present: present.has("scripts/main_helper.py"),
    },
    {
      path: "references/guide.md",
      label: "references/guide.md (domain reference)",
      kind: "recommended",
      present: present.has("references/guide.md"),
    },
    {
      path: "test_fixtures/",
      label: "test_fixtures/ (sample input files)",
      kind: "optional",
      present: pathStartsWith("test_fixtures/"),
    },
    {
      path: "assets/",
      label: "assets/ (templates, configs)",
      kind: "optional",
      present: pathStartsWith("assets/"),
    },
  ];
}

export default function GoldStandardChecklist({ installable }: GoldStandardChecklistProps) {
  const checklist = useMemo(() => buildChecklist(installable), [installable]);

  return (
    <div className="rounded-xl border border-outline-variant bg-surface-container-lowest p-6">
      <p className="font-mono text-[0.6875rem] uppercase tracking-wider text-on-surface-dim">
        Gold Standard Checklist
      </p>
      <p className="mt-2 text-sm text-on-surface-dim">
        What this package contains vs. the Skill Authoring Constraints in{" "}
        <code className="rounded bg-surface-container-high px-1">CLAUDE.md</code>.
      </p>
      <div className="mt-4 space-y-2">
        {checklist.map((item) => (
          <div
            key={item.path}
            className="flex items-start gap-3 rounded-lg bg-surface-container-low p-3"
          >
            <span
              className={`mt-0.5 font-mono text-sm ${
                item.present ? "text-tertiary" : "text-on-surface-dim"
              }`}
            >
              {item.present ? "✓" : "○"}
            </span>
            <div className="min-w-0 flex-1">
              <p className="font-mono text-xs text-on-surface">{item.label}</p>
              <p className="mt-0.5 font-mono text-[0.625rem] text-on-surface-dim">
                {item.kind} ·{" "}
                {item.present ? "present in this package" : "not generated by this run"}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
