"""Challenge Designer — auto-generates evaluation challenges from a specialization.

Uses the Claude Agent SDK ``query()`` with WebSearch enabled (gated by
``config.WEBSEARCH_ENABLED``) to ground challenges in real-world examples of
the specialization domain. Produces 3-5 challenges spanning easy/medium/hard
with distinct verification methods.
"""

from __future__ import annotations

import json
import re
import uuid

from claude_agent_sdk import ClaudeAgentOptions, query

from skillforge.config import WEBSEARCH_ENABLED, model_for
from skillforge.models import Challenge

# JSON schema description embedded in prompts
_SCHEMA_DESCRIPTION = """[
  {
    "prompt": "concrete task instruction to give Claude when the Skill is loaded",
    "difficulty": "easy" | "medium" | "hard",
    "evaluation_criteria": {"correctness": 0.4, "idiomaticity": 0.3, "robustness": 0.2, "simplicity": 0.1},
    "verification_method": "run_tests" | "judge_review" | "both",
    "setup_files": {"relative/path.py": "file contents"},
    "gold_standard_hints": "what a great solution looks like"
  }
]"""


def _extract_json_array(text: str) -> list[dict]:
    """Extract a JSON array from text.

    Tries fenced ```json ... ``` blocks first, then falls back to finding
    the first ``[`` and its matching ``]``.

    Raises:
        ValueError: if no valid JSON array can be extracted.
    """
    # 1. Try fenced block
    fence_match = re.search(r"```json\s*(.*?)```", text, re.DOTALL)
    if fence_match:
        candidate = fence_match.group(1).strip()
        try:
            result = json.loads(candidate)
            if isinstance(result, list):
                return result
        except json.JSONDecodeError:
            pass  # fall through to bracket search

    # 2. Fall back to first [ ... ] pair
    start = text.find("[")
    if start != -1:
        end = text.rfind("]")
        if end != -1 and end > start:
            candidate = text[start : end + 1]
            try:
                result = json.loads(candidate)
                if isinstance(result, list):
                    return result
            except json.JSONDecodeError:
                pass

    raise ValueError("No valid JSON array found in response text")


def _collect_text(messages: list) -> str:
    """Collect all text from assistant messages into a single string.

    Handles real ``AssistantMessage`` objects (content blocks with TextBlock)
    as well as duck-typed test fakes that expose ``.content`` with objects
    having a ``.text`` attribute.
    """
    parts: list[str] = []
    for msg in messages:
        content = getattr(msg, "content", None)
        if content is None:
            continue
        if isinstance(content, str):
            parts.append(content)
        elif isinstance(content, list):
            for block in content:
                # Real SDK: TextBlock has .text; fakes also have .text
                text_val = getattr(block, "text", None)
                if text_val is not None:
                    parts.append(text_val)
    return "\n".join(parts)


def _build_system_prompt(specialization: str, n: int) -> str:
    return (
        f"You design evaluation challenges for a Claude Skill specialized in: {specialization}. "
        f"Produce exactly {n} challenges spanning easy/medium/hard difficulty. "
        "Return ONLY a JSON array — no prose before or after — matching this schema:\n"
        f"{_SCHEMA_DESCRIPTION}\n"
        "Each object must have all six keys. The 'id' field is generated by Python; do NOT include it."
    )


def _build_retry_prompt(specialization: str, n: int) -> str:
    return (
        "Your previous response was not parseable JSON. "
        f"Respond with ONLY a JSON array of exactly {n} challenge objects matching this schema:\n"
        f"{_SCHEMA_DESCRIPTION}\n"
        "No explanation, no markdown prose — ONLY the JSON array."
    )


def _parse_challenges(raw: list[dict]) -> list[Challenge]:
    """Convert raw dicts into Challenge objects, generating UUIDs."""
    challenges: list[Challenge] = []
    for item in raw:
        challenges.append(
            Challenge(
                id=str(uuid.uuid4()),
                prompt=item["prompt"],
                difficulty=item["difficulty"],
                evaluation_criteria=item.get("evaluation_criteria", {}),
                verification_method=item.get("verification_method", "judge_review"),
                setup_files=item.get("setup_files", {}),
                gold_standard_hints=item.get("gold_standard_hints", ""),
            )
        )
    return challenges


async def design_challenges(specialization: str, n: int = 3) -> list[Challenge]:
    """Generate ``n`` challenges for the given specialization.

    Args:
        specialization: Description of the Skill domain to design challenges for.
        n: Number of challenges to generate. Defaults to 3.

    Returns:
        A list of exactly ``n`` Challenge objects with generated UUIDs.

    Raises:
        ValueError: if JSON cannot be parsed after 2 attempts, or if the
            number of returned challenges does not equal ``n``.
    """
    allowed_tools = ["WebSearch"] if WEBSEARCH_ENABLED else []
    options = ClaudeAgentOptions(
        permission_mode="dontAsk",
        allowed_tools=allowed_tools,
        model=model_for("challenge_designer"),
    )

    # Attempt 1
    system_prompt = _build_system_prompt(specialization, n)
    collected_msgs: list = []
    async for msg in query(prompt=system_prompt, options=options):
        collected_msgs.append(msg)

    text = _collect_text(collected_msgs)

    try:
        raw = _extract_json_array(text)
    except ValueError:
        # Attempt 2 — retry with more explicit prompt
        retry_prompt = _build_retry_prompt(specialization, n)
        collected_msgs = []
        async for msg in query(prompt=retry_prompt, options=options):
            collected_msgs.append(msg)

        text = _collect_text(collected_msgs)
        try:
            raw = _extract_json_array(text)
        except ValueError as err:
            raise ValueError(
                "challenge designer failed to produce valid JSON after 2 attempts"
            ) from err

    challenges = _parse_challenges(raw)

    if len(challenges) != n:
        raise ValueError(
            f"challenge designer returned {len(challenges)} challenges, expected {n}"
        )

    return challenges
